ContraCNO/urls.py
from django.contrib import admin
from django.urls import path, include
from app.Equipo import views as equipo
from app.usuario import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', equipo.Inicio.as_view(), name='Inicio'),
    path('ingreso/', auth.Ingreso.as_view(), name='Ingreso'),
    path('cierre/', auth.LogoutView.as_view(), name='Cierre'),
    path('equipo/', include(('app.Equipo.urls', 'Equipo',))),
    path('entrega/', include(('app.Entrega.urls', 'Entrega',))),
    path(
        'enrolamiento/', include(('app.Enrolamiento.urls', 'Enrolamiento',))
    ),
]

app/Entrega/urls.py
""" RUTAS DE ENTREGA DE DNI

Se detallan todas las rutas del módulo de entregas.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from django.urls import path
from . import views as v


urlpatterns = [
    path('actual', v.datos_actualizados, name='Actualizados'),
    path('centros', v.Centros.as_view(), name='Centros'),
    path('centros/crear', v.CrearCentro.as_view(), name='CrearCentro'),
    path('centros/<int:pk>/editar', v.EditarCentro.as_view(),
         name='EditarCentro'),
    path('centros/<int:pk>/eliminar', v.EliminarCentro.as_view(),
         name='EliminarCentro'),
    path('cajas', v.Cajas.as_view(), name='Cajas'),
    path('cajas/crear', v.CrearCaja.as_view(), name='CrearCaja'),
    path('cajas/<int:pk>', v.VerCaja.as_view(), name='VerCaja'),
    path('cajas/<int:pk>/editar', v.EditarCaja.as_view(), name='EditarCaja'),
    path('cajas/<int:pk>/eliminar', v.EliminarCaja.as_view(),
         name='EliminarCaja'),
    path('cajas/inventario', v.InventarioCaja.as_view(),
         name='InventarioCaja'),
    path('entregas', v.Entregas.as_view(), name='Entregas'),
    path('entregas/crear', v.CrearEntrega.as_view(), name='CrearEntrega'),
    path('entregas/crear-escaner', v.CrearEntregaEscaner.as_view(),
         name='CrearEntregaEscaner'),
    path('entregas/<int:pk>/eliminar', v.EliminarEntrega.as_view(),
         name='EliminarEntrega'),
    path('sobres/crear', v.CrearSobre.as_view(), name='CrearSobre'),
    path('sobres/<int:pk>/eliminar', v.EliminarSobre.as_view(),
         name='EliminarSobre'),
]

app/Entrega/models.py
""" MODELOS DE ENTREGA

Se detallan los modelos para el inventario de entrega de DNIs.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from django.db import models
from app.Equipo import models as m


class ManejadorCentro(models.Manager):
    """ Manejador de centros """

    def por_equipo(self, equipo: m.Equipo):
        return self.filter(equipo=equipo)


class Centro(models.Model):
    """ Representa un centro de entrega """

    id = models.BigAutoField(primary_key=True)
    equipo = models.ForeignKey(m.Equipo, on_delete=models.CASCADE,
                               related_name='centros')
    nombre = models.CharField(max_length=100, unique=False)

    objects = ManejadorCentro()
    _total_sobres = 0

    def __str__(self):
        return f'(Equipo: {self.equipo.nombre}) {self.nombre}'

    @property
    def total_sobres(self):
        """ Devuelve el número de sobres entregados """

        if not self._total_sobres:
            for cajas in self.cajas.all():
                self._total_sobres += cajas.sobres \
                    .filter(dato_entrega__isnull=False).count()

        return self._total_sobres

    class Meta:
        ordering = ('nombre',)


class ManejadorCaja(models.Manager):
    """ Manejador de cajas """

    def por_equipo(self, equipo: m.Equipo):
        return self.filter(centro__equipo=equipo)


class Caja(models.Model):
    """ Representa una caja de sobres """

    id = models.BigAutoField(primary_key=True)
    codigo = models.CharField(max_length=7, unique=False)
    centro = models.ForeignKey(Centro, on_delete=models.CASCADE,
                               related_name='cajas')
    cantidad_listado = models.PositiveIntegerField(default=0)

    objects = ManejadorCaja()

    @property
    def cantidad(self):
        """ Retorna la cantidad de sobres en la caja """
        return self.cantidad_listado if self.cantidad_listado != 0 \
            else self.sobres.count()

    @property
    def entregados(self):
        """ Retorna la cantidad de sobres entregadas """
        return self.sobres.filter(dato_entrega__isnull=False).count()

    @property
    def equipo(self) -> m.Equipo:
        return self.centro.equipo

    def __str__(self):
        return f'(Equipo: {self.equipo.nombre}) {self.codigo}'

    class Meta:
        ordering = ('codigo',)


class ManejadorSobre(models.Manager):
    """ Manejador de sobres """

    def por_equipo(self, equipo: m.Equipo):
        return self.filter(caja__centro__equipo=equipo)


class Sobre(models.Model):
    """ Representa un sobre de DNI """

    id = models.BigAutoField(primary_key=True)
    codigo = models.CharField(max_length=9, unique=False)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE,
                             related_name='sobres')

    objects = ManejadorSobre()

    @property
    def entregado(self):
        entregado = bool

        try:
            entregado = self.dato_entrega is not None
        except models.ObjectDoesNotExist:
            entregado = False

        return entregado

    @property
    def equipo(self) -> m.Equipo:
        return self.caja.centro.equipo

    def __str__(self):
        return f'(Equipo: {self.equipo.nombre}) ' \
               f'{self.codigo}-{self.caja.codigo}'

    class Meta:
        ordering = ('codigo',)


class ManejadorEntrega(models.Manager):
    """ Manejador de entregas """

    def por_equipo(self, equipo: m.Equipo):
        return self.filter(sobre__caja__centro__equipo=equipo)


class EntregaSobre(models.Model):
    """ Representa la entrega de un sobre en el sistema """

    id = models.BigAutoField(primary_key=True)
    sobre = models.OneToOneField(Sobre, on_delete=models.CASCADE,
                                 related_name='dato_entrega')
    hora_entrega = models.TimeField(auto_now_add=True)
    sede_entrega = models.ForeignKey(m.Sede, on_delete=models.CASCADE,
                                     related_name='sobres_entregados')
    enrolador_entrega = models.ForeignKey(m.Enrolador,
                                          on_delete=models.CASCADE,
                                          related_name='sobres_entregados')
    enrolador_escaner = models.ManyToManyField(
        m.Enrolador, blank=True,
        editable=False,
        related_name='sobres_escaneados'
    )

    objects = ManejadorEntrega()

    @property
    def fecha_entrega(self):
        return self.sede_entrega.fecha

    @property
    def equipo(self) -> m.Equipo:
        return self.sobre.caja.centro.equipo

    class Meta:
        ordering = ('-sede_entrega__fecha', '-hora_entrega',)

app/Entrega/views.py
""" VISTAS DE ENTREGA DNI

Se detallan todas las vistas para entregas de DNI.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from django.http import HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.utils.timezone import now
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from app.base import views as v
from . import models as m, forms as f


@login_required
def datos_actualizados(request, *args, **kwargs):
    """ Retorna datos actualizados del enrolador """

    if not request.user.colaborador.es_supervisor:
        enrolador = request.user.colaborador.enrolador

        entregados = enrolador.sobres_entregados.filter(
            sede_entrega__fecha=now().date()).count()
        enrolados = enrolador.unidad.enrolamientos.filter(
            sede__fecha=now().date())
        enrolados = enrolados.first().cantidad_enrol + \
            enrolados.first().cantidad_actua if enrolados else 0
        escaneados = enrolador.sobres_escaneados.filter(
            sede_entrega__fecha=now().date()).count()

        return HttpResponse(str([entregados, enrolados, escaneados]))
    else:
        return HttpResponse(str([0, 0, 0]))


@method_decorator(login_required, 'dispatch')
class Centros(v.VistaLista):
    """ Muestra una lista de todos los centros """

    model = m.Centro
    template_name = 'centros.html'
    paginate_by = 10

    def get_queryset(self):
        """ Añade términos de búsqueda """

        query = super().get_queryset()

        if 'buscar' in self.request.GET and self.request.GET['buscar'] \
                is not None:

            buscar = self.request.GET['buscar']
            query = query.filter(nombre__icontains=buscar)

        return query


@method_decorator(login_required, 'dispatch')
class CrearCentro(v.VistaCrear):
    """ Crea un nuevo centro en el sistema """

    model = m.Centro
    template_name = 'crear-centro.html'
    form_class = f.FormCentro
    success_url = reverse_lazy('Entrega:Centros')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se registró el centro correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EditarCentro(v.VistaEditar):
    """ Edita un centro en el sistema """

    model = m.Centro
    template_name = 'crear-centro.html'
    form_class = f.FormCentro
    success_url = reverse_lazy('Entrega:Centros')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se editó el centro correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EliminarCentro(v.VistaEliminar):
    """ Elimina un centro del sistema """

    model = m.Centro
    template_name = 'eliminar-centro.html'
    success_url = reverse_lazy('Entrega:Centros')


@method_decorator(login_required, 'dispatch')
class VerCaja(v.VistaVer):
    """ Visualiza los detalles de una caja en el sistema """

    model = m.Caja
    template_name = 'ver-caja.html'

    def obtener_sobres(self):
        """ Obtiene la lista de sobres de la caja """

        sobres = m.Sobre.objects.filter(caja=self.get_object())

        if 'buscar' in self.request.GET \
                and self.request.GET['buscar'] is not None:
            sobres = sobres.filter(
                codigo__icontains=self.request.GET['buscar'])

        return sobres

    def get_context_data(self, **kwargs):
        """ Añade la lista de sobres de la caja """

        ctx = super().get_context_data(**kwargs)
        sobres = self.obtener_sobres()
        pagina = Paginator(sobres, 10)

        if 'page' in self.request.GET and self.request.GET['page'] is not None:
            ctx['page_obj'] = pagina.get_page(self.request.GET['page'])
        else:
            ctx['page_obj'] = pagina.get_page(1)

        return ctx


@method_decorator(login_required, 'dispatch')
class Cajas(v.VistaLista):
    """ Muestra una lista de cajas """

    model = m.Caja
    template_name = 'cajas.html'
    paginate_by = 10

    def get_queryset(self):
        """ Agrega los términos de búsqueda del formulario """

        query = super().get_queryset()

        if 'buscar' in self.request.GET and self.request.GET['buscar'] \
                is not None:

            buscar = self.request.GET['buscar']
            query = query.filter(
                Q(codigo__icontains=buscar)
                | Q(centro__nombre__icontains=buscar))

        return query


@method_decorator(login_required, 'dispatch')
class CrearCaja(v.VistaCrear):
    """ Crea una caja en el sistema """

    model = m.Caja
    template_name = 'crear-caja.html'
    form_class = f.FormCajaCrear
    success_url = reverse_lazy('Entrega:Cajas')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """
        messages.success(self.request, 'Se creó la caja correctamente')

        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EditarCaja(v.VistaEditar):
    """ Edita una caja en el sistema """

    model = m.Caja
    template_name = 'crear-caja.html'
    form_class = f.FormCajaCrear
    success_url = reverse_lazy('Entrega:Cajas')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          editable=True,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se editó la caja correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EliminarCaja(v.VistaEliminar):
    """ Elimina una caja en el sistema """

    model = m.Caja
    template_name = 'eliminar-caja.html'
    success_url = reverse_lazy('Entrega:Cajas')


@method_decorator(login_required, 'dispatch')
class InventarioCaja(FormView):
    """ Hace un inventario final de la caja """

    form_class = f.FormCajaInventario
    template_name = 'crear-caja.html'

    def form_valid(self, form):
        sobres = form.save()
        sobres.delete()

        messages.success(self.request, 'Inventario de caja exitoso')

        return redirect(reverse_lazy('Entrega:InventarioCaja'))

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          editable=False,
                          **self.get_form_kwargs())


@method_decorator(login_required, 'dispatch')
class Entregas(v.VistaLista):
    """ Muestra una lista de sobres """

    model = m.EntregaSobre
    template_name = 'entregas.html'
    paginate_by = 10

    def get_queryset(self):
        """ Agrega los términos de búsqueda del formulario """

        query = super().get_queryset()

        if not self.request.user.colaborador.es_supervisor:
            query = query.filter(
                enrolador_entrega=self.request.user.colaborador.enrolador)

        if 'buscar' in self.request.GET and self.request.GET['buscar'] \
                is not None:

            buscar = self.request.GET['buscar']
            query = query.filter(
                Q(sobre__codigo__icontains=buscar) |
                Q(sobre__caja__codigo__icontains=buscar) |
                Q(sobre__caja__centro__nombre__icontains=buscar))

        return query


@method_decorator(login_required, 'dispatch')
class CrearEntrega(v.VistaCrear):
    """ Crea un sobre en el sistema """

    model = m.EntregaSobre
    template_name = 'crear-sobre.html'
    form_class = f.FormEntrega
    sede = m.m.Sede
    success_url = reverse_lazy('Entrega:CrearEntrega')

    def dispatch(self, request, *args, **kwargs):
        """ Alerta si hay sede para trabajar en entregas """

        if request.user.colaborador.es_supervisor:
            return redirect(reverse_lazy('Equipo:Sedes'))

        self.sede = self.request.user.colaborador.enrolador.sedes_entrega \
            .filter(fecha=now(), hora_inicio__lte=now(),
                    hora_final__gt=now()).first()

        if self.sede:
            return super().dispatch(request, *args, **kwargs)
        else:
            messages.warning(
                request, 'No hay sede configurada para el día de '
                'hoy, notifique al supervisor para agregar una.')
            return redirect(reverse_lazy('Equipo:Sedes'))

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          **self.get_form_kwargs())

    def form_valid(self, form: form_class):
        entrega = form.save(commit=False)
        entrega.sede_entrega = self.sede
        sobre = m.Sobre.objects.get(codigo=entrega.sobre.codigo,

app/Entrega/templates/cajas.html
{% extends 'base.html' %}

{% comment %}
PLANTILLA DE LISTA DE CAJAS

Esta plantilla muestra un listado de cajas de un equipo.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'TituloContenido' %}Cajas de DNIs{% endblock %}
{% block 'Titulo' %}Cajas{% endblock %}

{% load mathfilters %}

{% block 'Contenido' %}
<div class="row">
  <div class="col-sm-12">
    <div class="card card-outline card-orange">
      <div class="card-header">
        <h3 class="card-title text-lg">Lista de cajas</h3>
        <div class="card-tools d-flex">
          <a class="btn btn-tool btn-sm d-flex mt-1" href="{% url 'Entrega:CrearCaja' %}"><i class="fas fa-archive"></i><i class="fas fa-plus text-sm"></i></a>
          <a class="btn btn-tool btn-sm text-danger d-flex mt-1" href="{% url 'Entrega:InventarioCaja' %}"><i class="fas fa-archive"></i><i class="fas fa-times text-sm"></i></a>
          <form class="input-group input-group-sm" action="">
	    <input type="text" name="buscar" placeholder="Buscar..." class="form-control" value="{{ request.GET.buscar }}">
	    <div class="input-group-append">
	      <button class="btn btn-default" type="submit"><i class="fas fa-search"></i></button>
	    </div>
	  </form>
        </div>
      </div>
      <div class="card-body table-responsive">
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Código</th>
	      <th>Centro</th>
	      <th>Inicio</th>
	      <th>Entregadas</th>
	      <th>Final</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for caja in page_obj %}
	    <tr>
	      <td>{{ caja.codigo }}</td>
	      <td>{{ caja.centro.nombre }}</td>
	      <td>{{ caja.cantidad }}</td>
	      <td>{{ caja.entregados }}</td>
	      <td>{{ caja.cantidad | sub:caja.entregados}}</td>
	      <td>
           <a class="btn btn-sm btn-primary" href="{% url 'Entrega:VerCaja' caja.pk %}"><i class="fas fa-eye"></i></a>
	      {% if user.is_staff or user.colaborador.es_supervisor %}
		<a class="btn btn-sm btn-secondary" href="{% url 'Entrega:EditarCaja' caja.pk %}"><i class="fas fa-edit text-sm"></i></a>
		<a class="btn btn-sm btn-danger" href="{% url 'Entrega:EliminarCaja' caja.pk %}"><i class="fas fa-trash"></i></a>
           {% endif %}
	      </td>
	    </tr>
	    {% empty %}
	    <div class="alert alert-info">
	      <h5><i class="fa fa-exclamation-triangle"></i> No hay cajas registradas</h5>
	      <p>No se encuentran cajas registradas en el sistema</p>
	    </div>
	    {% endfor %}
	  </tbody>
	</table>
      </div>
      <div class="card-footer">
        {% include 'paginacion.html' %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/Entrega/templates/centros.html
{% extends 'base.html' %}

{% block 'TituloContenido' %}Centros de entrega{% endblock %}
{% block 'Titulo' %}Centros de entrega{% endblock %}

{% block 'Contenido' %}
<div class="row">
  <div class="col-sm-12">
    <div class="card card-outline card-orange">
      <div class="card-header">
        <h3 class="card-title text-lg">Lista de centros</h3>
        <div class="card-tools d-flex">
        <a class="btn btn-tool btn-sm d-flex mt-1" href="{% url 'Entrega:CrearCentro' %}"><i class="fas fa-building"></i><i class="fas fa-plus text-sm"></i></a>
	  <form class="input-group input-group-sm" action=""> 
	    <input class="form-control" type="text" placeholder="Buscar..." name="buscar" value="{{ request.GET.buscar }}">
	    <div class="input-group-append"><button class="btn btn-default" type="submit"><i class="fas fa-search"></i></button></div>
	  </form>
	</div>
      </div>
      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead>
	    <tr>
	      <th>Nombre</th>
	      <th>Cajas</th>
	      <th>Sobres entregados</th>
	    </tr>
	  </thead>
          <tbody>
	    {% for centro in page_obj %}
	    <tr>
	      <td>{{ centro.nombre }}</td>
	      <td>{{ centro.cajas.count }}</td>
	      <td>{{ centro.total_sobres }}</td>
	      <td class="text-center">
            <a class="btn btn-primary text-sm btn-sm" data-toggle="tooltip" title="Ver las cajas de este centro" href="{% url 'Entrega:Cajas' %}?buscar={{ centro.nombre  | iriencode }}"><i class="fas fa-archive"></i></a>
            {% if user.is_staff or user.colaborador.es_supervisor %}
            <a class="btn btn-secondary text-sm btn-sm" href="{% url 'Entrega:EditarCentro' centro.pk %}"><i class="fas fa-edit"></i></a>
            <a class="btn btn-danger btn-sm text-sm" href="{% url 'Entrega:EliminarCentro' centro.pk %}"><i class="fas fa-trash"></i></a>
            {% endif %}
           </td>
	      {% empty %}
	      <div class="alert alert-info">
	        <h5>
	          <i class="fas fa-exclamation-triangle"></i>
                No hay centros de entrega en el sistema
	        </h5>
	        <p>Todavía no se registran centros de entrega en el sistema</p>
	      </div>
	      {% endfor %}
	    </tr>
	  </tbody>
    </table>
    </div>
    <div class="card-footer">{% include 'paginacion.html' %}</div>
    </div>
  </div>
</div>
{% endblock %}

app/Entrega/templates/crear-caja.html
{% extends 'base.html' %}
{% load staticfiles %}

{% comment %}
PLANTILLA DE FORMULARIO DE CAJAS

Esta plantilla muestra un formulario para la edición de cajas.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Titulo' %}Registrar Caja{% endblock %}
{% block 'TituloContenido' %}Registrar caja de DNI's{% endblock %}

{% block 'Contenido' %}
<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8">
    <div class="card card-outline card-orange">
      <div class="card-header">
        <h3 class="card-title">Registro de caja</h3>
      </div>
      <div class="card-body">
	<form id="FormCaja" action="" enctype="multipart/data-form" method="POST">
	  {% csrf_token %}
	  <div class="form-group">
        <div class="input-group">
        	<div class="input-group-prepend"><span class="input-group-text"><i class="fas fa-archive"></i></span></div>
            {{ form.codigo }}
            <div class="input-group-append"><button data-toggle="modal" data-target="#escaner" class="btn btn-primary" type="button"><i class="fas fa-qrcode"></i></button></div>
        </div>
	    {% if form.errors.codigo %}<span class="text-sm text-danger">{{ form.errors.codigo }}</span>{% endif %}
	  </div>
	  <div class="form-group">
        <div class="input-group">
        	<div class="input-group-prepend"><span class="input-group-text"><i class="fas fa-building"></i></span></div>
            {{ form.centro }}
        </div>
	    {% if form.errors.centro %}<span class="text-sm text-danger">{{ form.errors.centro }}</span>{% endif %}
	  </div>
	  {% if form.sobres %}
	  <div class="form-group">
        <label>Sobres:</label><a href="#" data-toggle="modal" data-target="#escaner" class="btn btn-sm btn-tool"><i class="fas fa-envelope"></i><i class="fas fa-plus text-sm"></i></a>
        {{ form.sobres }}
	    {% if form.errors.sobres %}<span class="text-sm text-danger">{{ form.errors.sobres }}</span>{% endif %}
	  </div>
	  {% endif %}
	</form>
      </div>
      <div class="card-footer">
        <button class="btn btn-success btn-block" type="submit" form="FormCaja">Registrar</button>
        <a class="btn btn-block btn-danger" href="{% url 'Entrega:Cajas' %}">Cancelar</a>
       </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
{% include 'escaner.html' %}
{% endblock %}
{% block 'OtrosGuiones' %}
<script src="{% static 'plugins/html5-qrcode/html5-qrcode.min.js' %}"></script>
<script src="{% static 'escaner.js' %}"></script>
<script src="{% static 'editar-caja.js' %}"></script>
{% include 'overlay-card.html' %}
{% endblock %}

app/Entrega/templates/crear-centro.html
{% extends 'base.html' %}

{% block 'TituloContenido' %}Crear/Editar centro de entrega{% endblock %}

{% block 'Contenido' %}
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="card card-outline card-orange">
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre del centro:</label>
                {{ form.nombre }}
                {% if form.errors.nombre %}<span class="text-sm text-danger">{{ form.errors.nombre }}</span>{% endif %}
            </div>
            <button class="btn btn-success btn-block" type="submit">Guardar</button>
            <a class="btn btn-block btn-danger" href="{% url 'Entrega:Centros' %}">Cancelar</a>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
{% endblock %}
{% block 'OtrosGuiones' %}
{% include 'overlay-card.html' %}
{% endblock %}

app/Entrega/templates/crear-sobre-escaner.html
{% extends 'crear-sobre.html' %}

{% comment %}
PLANTILLA DE ESCANER DE SOBRE PARA OTRO ENROLADOR

Se genera un formulario para escanear sobres de otro enrolador.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'FormUsuario' %}
<div class="form-group">
    <div class="input-group">
        <div class="input-group-prepend"><span class="input-group-text"><i class="fas fa-user"></i></span></div>
        {{ form.enrolador_entrega }}
    </div>
    {% if form.errors.enrolador_entrega %} <span class="text-sm text-danger">{{ form.enrolador_entrega.errors }}</span>{% endif %}
</div>
{% endblock %}

app/Entrega/templates/eliminar-caja.html
{% extends 'eliminar.html' %}

{% comment %}
PLANTILLA DE ELIMINACIÓN DE CAJAS.
Esta plantilla sirve para confirmar la eliminación de una caja del sistema.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Mensaje' %}la caja {{ object.codigo }}{% endblock %}
{% block 'Advertencia' %}
Recuerde que se borrarán los sobres y entregas asociadas a este registro.
{% endblock %}
{% block 'Cancelar' %}{% url 'Entrega:Cajas' %}{% endblock %}

app/Entrega/templates/eliminar-centro.html
{% extends 'eliminar.html' %}

{% comment %}
PLANTILLA DE ELIMINACIÓN DE CENTROS.

Esta plantilla sirve para confirmar la eliminación de un centro del sistema.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Mensaje' %}el centro {{ object.nombre }}{% endblock %}
{% block 'Advertencia' %}
Recuerde que se borrarán las cajas, sobres y entregas asociadas a este registro
{% endblock %}
{% block 'Cancelar' %}{% url 'Entrega:Centros' %}{% endblock %}