ContraCNO/urls.py
from django.contrib import admin
from django.urls import path, include
from app.Equipo import views as equipo
from app.usuario import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', equipo.Inicio.as_view(), name='Inicio'),
    path('ingreso/', auth.Ingreso.as_view(), name='Ingreso'),
    path('cierre/', auth.LogoutView.as_view(), name='Cierre'),
    path('equipo/', include(('app.Equipo.urls', 'Equipo',))),
    path('entrega/', include(('app.Entrega.urls', 'Entrega',))),
    path(
        'enrolamiento/', include(('app.Enrolamiento.urls', 'Enrolamiento',))
    ),
]

app/Equipo/urls.py
""" RUTAS DE EQUIPO

Se detallan las rutas de acceso de los equipos.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from django.urls import path
from . import views as v

urlpatterns = [
        path('sedes', v.Sedes.as_view(), name='Sedes'),
        path('sedes/crear', v.CrearSede.as_view(), name='CrearSede'),
        path('sedes/<int:pk>', v.VerSede.as_view(), name='VerSede'),
        path('sedes/<int:pk>/editar', v.EditarSede.as_view(),
             name='EditarSede'),
        path('sedes/<int:pk>/eliminar', v.EliminarSede.as_view(),
             name='EliminarSede'),
        path('domiciliaria/crear', v.CrearDomiciliaria.as_view(),
             name='CrearDomiciliaria'),
        path('domiciliaria/<int:pk>/editar', v.EditarDomiciliaria.as_view(),
             name='EditarDomiciliaria'),
]

app/Equipo/models.py
""" MODOELOS DE EQUIPO

Definen los elementos básicos de un equipo en el proyecto Identifícate.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Colaborador(models.Model):
    """ Representa un supervisor en el sistema """

    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE,
                                   related_name='colaborador')
    es_supervisor = models.BooleanField(editable=False, default=False)

    @property
    def nbreve(self):
        nombre = self.nombre
        return nombre.split(' ')[0]

    @property
    def abreve(self):
        return self.apellido.split(' ')[0]

    @property
    def equipo(self):
        equipo = None

        if self.es_supervisor:
            try:
                equipo = self.supervisor.equipo
            except models.ObjectDoesNotExist:
                pass
        else:
            equipo = self.enrolador.equipo

        return equipo

    def __str__(self):
        return f'{self.nombre} {self.apellido}'


class Supervisor(Colaborador):
    """ Representa a un supervisor del proyecto """

    def save(self):
        """ Marca como supervisor """

        self.es_supervisor = True
        super().save()

    def __str__(self):
        return f'{self.nombre} {self.apellido}'

    class Meta:
        verbose_name = 'supervisor'
        verbose_name_plural = 'supervisores'


class Equipo(models.Model):
    """ Representa un equipo del proyecto """

    id = models.BigAutoField(primary_key=True)
    supervisor = models.OneToOneField(Supervisor, on_delete=models.CASCADE,
                                      related_name='equipo')
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nombre} (Supervisor: {self.supervisor.nombre})'

    class Meta:
        verbose_name = 'equipo'
        verbose_name_plural = 'equipos'


class ManejadorUnidad(models.Manager):
    """ Manejador de unidad """

    def por_equipo(self, equipo: Equipo):
        return self.filter(equipo=equipo)


class Unidad(models.Model):
    """ Representa una UME en el sistema """

    id = models.BigAutoField(primary_key=True)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE,
                               related_name='unidades')
    nombre = models.CharField(max_length=50, blank=True)
    kit = models.CharField(max_length=4, blank=True)

    objects = ManejadorUnidad()

    def __str__(self):
        return f'Unidad {self.nombre}'

    class Meta:
        verbose_name = 'UME'
        verbose_name_plural = 'UMEs'


class ManejadorEnrolador(models.Manager):
    """ Manejador de enroladores """

    def por_equipo(self, equipo: Equipo):
        return self.filter(unidad__equipo=equipo)


class Enrolador(Colaborador):
    """ Representa un enrolador en el sistema """

    unidad = models.ForeignKey(Unidad, on_delete=models.CASCADE,
                               related_name='enroladores')
    usuario_dominio = models.CharField(max_length=50, blank=True)

    objects = ManejadorEnrolador()

    @property
    def equipo(self):
        return self.unidad.equipo

    def save(self):
        """ Marca como no supervisor """

        self.es_supervisor = False
        super().save()

    class Meta:
        verbose_name = 'enrolador'
        verbose_name_plural = 'enroladores'


class ManejadorSede(models.Manager):
    """ Manejador de sedes """

    def por_equipo(self, equipo: Equipo):
        return self.filter(equipo=equipo)


class Sede(models.Model):
    """ Representa una sede de entrega/enrolamiento """

    id = models.BigAutoField(primary_key=True)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE,
                               related_name='sedes')
    fecha = models.DateField(default=timezone.now)
    hora_inicio = models.TimeField()
    hora_final = models.TimeField()
    nombre = models.CharField(max_length=100, unique=False, blank=True)
    lugar = models.CharField(max_length=100, unique=False, blank=True)
    es_domiciliaria = models.BooleanField(default=False)

    enroladores = models.ManyToManyField(Unidad, blank=True,
                                         related_name='sedes_enrolamiento')
    entregadores = models.ManyToManyField(Enrolador, blank=True,
                                          related_name='sedes_entrega')

    objects = ManejadorSede()

    @property
    def total_entregadas(self):
        """ Retorna el total de DNIs entregadas """

        return self.sobres_entregados.count()

    @property
    def total_enrolados(self):
        """ Retorna el total de enrolamientos """
        from functools import reduce

        enrolamientos = self.enrolamientos.all().values('cantidad_enrol')

        return reduce(lambda acum, val: acum + val['cantidad_enrol'],
                      enrolamientos, 0)

    @property
    def total_actualizados(self):
        """ Retorna el total de enrolamientos """
        from functools import reduce

        enrolamientos = self.enrolamientos.all().values('cantidad_actua')

        return reduce(lambda acum, val: acum + val['cantidad_actua'],
                      enrolamientos, 0)

    def __str__(self):
        return f'[Equipo: {self.equipo.nombre}] {self.nombre} de {self.lugar}'

    class Meta:
        verbose_name = 'sede'
        verbose_name_plural = 'sedes'
        ordering = ('-fecha', '-es_domiciliaria', '-hora_inicio',)

app/Equipo/forms.py
""" FORMULARIO DE EQUIPO

Se detallan todos los formularios de los equipos del proyecto.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from app.base.forms import FormularioBootstrap, f
from . import models as m


class FormDomiciliaria(FormularioBootstrap, f.ModelForm):
    """ Formulario de edición de domiciliarias """

    def __init__(self, equipo: m.Equipo, editable: bool = False,
                 *args, **kwargs):
        """ Añadiendo soporte de horas en TimeFields """

        super().__init__(equipo, editable, *args, **kwargs)

        self.fields['hora_inicio'].input_formats = self.fields['hora_final'] \
            .input_formats = ('%I:%M %p',)
        self.fields['enroladores'].queryset = m.Unidad.objects.por_equipo(
            self.equipo)
        self.fields['entregadores'].queryset = m.Enrolador.objects.por_equipo(
            self.equipo)

    class Meta:
        model = m.Sede
        fields = ('nombre', 'lugar', 'fecha', 'hora_inicio', 'hora_final',
                  'enroladores', 'entregadores',)
        widgets = {
                'hora_inicio': f.TimeInput(
                    attrs={'class': 'datetimepicker-input',
                           'data-target': '#hora_inicio'}),

                'hora_final': f.TimeInput(
                    attrs={'class': 'datetimepicker-input',
                                    'data-target': '#hora_final'}),

                'fecha': f.DateInput(
                    attrs={'class': 'datetimepicker-input',
                           'data-target': '#fecha'})
        }

    def save(self, commit: bool = True) -> m.Sede:
        """ Asigna el equipo del usuario """

        sede = super().save(commit=False)
        sede.equipo = self.equipo
        sede.es_domiciliaria = True
        sede.save()

        self.save_m2m()

        if commit:
            sede.save()

        return sede


class FormSede(FormDomiciliaria):
    """ Formulario de edición de sedes """

    def __init__(self, equipo: m.Equipo, editable: bool = False,
                 *args, **kwargs):
        """ Añade un filtro de gente que está en otra zona """

        super().__init__(equipo, editable, *args, **kwargs)

    def save(self, commit: bool = True) -> m.Sede:
        """ Asigna la sede como no domiciliaria """

        sede = super().save(commit=False)
        sede.es_domiciliaria = False
        sede.save()
        print(sede.es_domiciliaria)

        if commit:
            sede.save()

        return sede

app/Equipo/views.py
""" VISTAS DE EQUIPO

Se detallan las vistas que están relacionadas con los equipos del proyecto.

Autor: Carlos E. Rivera
Licencia: GPLv3
"""

from functools import reduce
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from app.base import views as v
from . import models as m, forms as f
from app.Entrega.models import EntregaSobre
from app.Enrolamiento.models import Enrolamiento


@method_decorator(login_required, 'dispatch')
class Inicio(v.VistaPlantilla):
    template_name = 'base.html'


@method_decorator(login_required, 'dispatch')
class Sedes(v.VistaLista):
    """ Obtiene el listado de sedes de un equipo """

    model = m.Sede
    template_name = 'sedes.html'
    paginate_by = 10


@method_decorator(login_required, 'dispatch')
class VerSede(v.VistaVer):
    """ Visualiza los datos de una sede """

    model = m.Sede
    template_name = 'ver-sede.html'

    def get_context_data(self, **kwargs):
        """ Añade los datos de entregas por enrolador """

        ctx = super().get_context_data(**kwargs)
        equipo = self.request.user.colaborador.equipo
        sede = ctx['object']
        enroladores = m.Enrolador.objects.por_equipo(equipo) \
            .filter(sedes_entrega=sede)

        # Datos de contexto
        enroladores_ctx = list()

        for enrolador in enroladores:
            enroladores_ctx.append({
                'nombre':
                f'{enrolador.nbreve} {enrolador.abreve}',
                'entregados':
                enrolador.sobres_entregados.filter(sede_entrega=sede).count(),
                'escaneados':
                enrolador.sobres_escaneados.filter(sede_entrega=sede).count(),
            })

        ctx['enroladores'] = enroladores_ctx
        ctx['gran_total_entrega'] = EntregaSobre.objects.por_equipo(equipo) \
            .filter(sede_entrega__fecha__lte=self.get_object().fecha).count()
        enrolamiento_totales = Enrolamiento.objects.por_equipo(equipo) \
            .filter(sede__fecha__lte=self.get_object().fecha).values(
                'cantidad_enrol', 'cantidad_actua')
        ctx['gran_total_enrol'] = reduce(
            lambda acum, val: acum + val['cantidad_enrol'],
            enrolamiento_totales, 0)
        ctx['gran_total_actua'] = reduce(
            lambda acum, val: acum + val['cantidad_actua'],
            enrolamiento_totales, 0)

        return ctx


@method_decorator(login_required, 'dispatch')
class CrearSede(v.VistaCrear):
    """ Crea una sede en el sistema """

    model = m.Sede
    template_name = 'crear-sede.html'
    form_class = f.FormSede
    success_url = reverse_lazy('Equipo:Sedes')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se registró la sede correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EditarSede(v.VistaEditar):
    """ Edita una sede en el sistema """

    model = m.Sede
    template_name = 'crear-sede.html'
    form_class = f.FormSede
    success_url = reverse_lazy('Equipo:Sedes')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          editable=True,
                          **self.get_form_kwargs())

    def form_valid(self, form: form_class):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se editó la sede correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class CrearDomiciliaria(CrearSede):
    """ Crea una visita domiciliaria en el sistema """

    form_class = f.FormDomiciliaria


@method_decorator(login_required, 'dispatch')
class EditarDomiciliaria(v.VistaEditar):
    """ Edita una visita domiciliaria en el sistema """

    model = m.Sede
    template_name = 'crear-sede.html'
    form_class = f.FormDomiciliaria
    success_url = reverse_lazy('Equipo:Sedes')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        return form_class(self.request.user.colaborador.equipo,
                          editable=True,
                          **self.get_form_kwargs())

    def form_valid(self, form):
        """ Añade un mensaje de éxito """

        messages.success(self.request, 'Se editó la sede correctamente')
        return super().form_valid(form)


@method_decorator(login_required, 'dispatch')
class EliminarSede(v.VistaEliminar):
    """ Elimina una sede del sistema """

    model = m.Sede
    template_name = 'eliminar-sede.html'
    success_url = reverse_lazy('Equipo:Sedes')

app/Equipo/templates/crear-sede.html
{% extends 'base.html' %}

{% comment 'PLANTILLA DE CREAR SEDE' %}

Esta plantilla contiene un formulario para crear una sede en el sistema.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% load staticfiles %}

{% block 'Titulo'%}Crear sede{% endblock %}
{% block 'TituloContenido' %}Registrar nueva sede{% endblock %}

{% block 'Contenido' %}
<div class="card card-solid p-0">
  <div class="card-body">
    <form id="FormSede" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
	<div class="col-sm-6">
	  <div class="card card-outline card-orange">
	    <div class="card-header">
	      <h3 class="text-lg card-title">Ubicación de la sede</h3>
	    </div>
	    <div class="card-body">
	      <div class="form-group">
	        <div class="input-group">
	          <div class="input-group-prepend">
	            <span class="input-group-text">
                    {% if object and object.es_domiciliaria %}
                    <i class="fas fa-home"></i>
                    {% else %}
                    <i class="fas fa-building"></i>
                    {% endif %}
	            </span>
	          </div>
		  {{ form.nombre }}
	        </div>
		{% if form.nombre.errors %}<span class="text-sm text-danger">{{ form.nombre.errors}}</span>{% endif %}
	      </div>
	      <div class="form-group">
	        <div class="input-group">
	          <div class="input-group-prepend">
	            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
	          </div>
		  {{ form.lugar }}
	        </div>
		{% if form.lugar.errors %}<span class="text-sm text-danger">{{ form.lugar.errors}}</span>{% endif %}
	      </div>
	    </div>
	  </div>
	  <div class="card card-outline card-orange">
	    <div class="card-header">
	      <h3 class="card-title text-lg">Horarios</h3>
	    </div>
	    <div class="card-body">
	      <div class="form-group">
		<div class="input-group date" id="fecha" data-target-input="nearest">
		  {{ form.fecha }}
		  <div class="input-group-append" data-target="#fecha" data-toggle="datetimepicker">
		    <span class="input-group-text"><i class="fas fa-calendar"></i></span>
		  </div>
		</div>
		{% if form.fecha.errors %}<span class="text-sm text-danger">{{ form.fecha.errors}}</span>{% endif %}
	      </div>
	      <div class="form-group">
	        <div id="hora_inicio" class="input-group date" data-target-input="nearest">
		  {{ form.hora_inicio }}
	          <div class="input-group-append" data-target="#hora_inicio" data-toggle="datetimepicker">
	            <span class="input-group-text"><i class="fas fa-clock"></i></span>
	          </div>
	        </div>
	      </div>
	      <div class="form-group">
	        <div id="hora_final" class="input-group date" data-target-input="nearest">
		  {{ form.hora_final }}
	          <div class="input-group-append" data-target="#hora_final" data-toggle="datetimepicker">
	            <span class="input-group-text"><i class="fas fa-clock"></i></span>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="col-sm-6">
	  <div class="card card-outline card-orange">
	    <div class="card-header">
	      <h3 class="card-title text-lg">Personal</h3>
	    </div>
	    <div class="card-body">
	      <div class="form-group">
		<label for="id_{{ form.enroladores.label | lower }}">{{ form.enroladores.label }}</label>
		{{ form.enroladores }}
		{% if form.enroladores.errors %}<span class="text-sm text-danger">{{ form.enroladores.errors}}</span>{% endif %}
	      </div>
	      <div class="form-group">
		<label for="id_{{ form.entregadores.label | lower }}">{{ form.entregadores.label }}</label>
		{{ form.entregadores }}
		{% if form.entregadores.errors %}<span class="text-sm text-danger">{{ form.entregadores.errors}}</span>{% endif %}
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </form>
  </div>
  <div class="card-footer">
    <button class="btn btn-block btn-success" form='FormSede'>Registrar</button>
    <a class="btn btn-block btn-danger" href="{% url 'Equipo:Sedes' %}">Cancelar</a>
  </div>
</div>
{% endblock %}
{% block 'OtrosEstilos' %}
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
{% endblock %}
{% block 'OtrosGuiones' %}
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<script>
  {% if not object %}
  $(document).ready(function() {
    $('#id_entregadores>option').prop('selected', true);
  });
  {% endif %}

  $('#fecha').datetimepicker({
    format: 'DD/MM/yyyy'
  });

  $('#hora_inicio').datetimepicker({
    format: 'LT'
  });

  $('#hora_final').datetimepicker({
    format: 'LT'
  });
  
  $('form').submit(function() {
    const overlay = '<div class="overlay dark"><i class="fas fa-sync fa-spin"></i></div>';
    $('div.card.card-solid').append(overlay);
  });
</script>
{% if form.errors %}
{% include 'error-formulario.html' %}
{% endif %}
{% endblock %}

app/Equipo/templates/eliminar-sede.html
{% extends 'eliminar.html' %}

{% comment %}
PLANTILLA DE ELIMINAR SEDE

Muestra un formulario para confirmar la eliminación de una sede.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Mensaje' %}la sede {{ object.nombre }} de {{ object.lugar }}{% endblock %}
{% block 'Advertencia' %}
Recuerde que al eliminarla se borrarán las entregas realizadas en este registro.
{% endblock %}
{% block 'Cancelar' %}{% url 'Equipo:Sedes' %}{% endblock %}

app/Equipo/templates/sedes.html
{% extends 'base.html' %}

{% comment  %}
PLANTILLA DE LISTA DE SEDES

Esta plantilla muestra la lista de sedes del equipo.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Titulo' %}Sedes{% endblock %}
{% block 'TituloContenido' %}Sedes{% endblock %}

{% block 'Contenido' %}
<div class="row">
  <div class="card col-sm-12 card-outline card-orange">
    <div class="card-header">
      <h3 class="card-title text-lg">Línea de tiempo</h3>

      <div class="card-tools">
	{% if user.es_supervisor or user.is_staff %}
	<a class="btn btn-tool btn-sm" href="{% url 'Equipo:CrearSede' %}">
	  <i class="fas fa-building"></i><i class="fas fa-plus text-sm"></i>
	</a>
	<a class="btn btn-tool btn-sm" href="{% url 'Equipo:CrearDomiciliaria' %}">
	  <i class="fas fa-home"></i><i class="fas fa-plus text-sm"></i>
	</a>
	{% endif %}
	{# TODO: Crear formulario de búsqueda #}
      </div>
    </div>
    {% if page_obj %}
    <div class="card-body">
      <div class="timeline">
          {% regroup page_obj by fecha as sedes_list %}
          {% for sedes in sedes_list %}
          <div class="time-label">
              <span class="bg-green">{{ sedes.grouper }}</span>
          </div>
          {% for sede in sedes.list %}
          <div>
	      {% if sede.es_domiciliaria %}
	      <i class="fas fa-home bg-warning"></i>
	      {% else %}
              <i class="fas fa-building bg-primary"></i>
	      {% endif %}
              <div class="timeline-item">
                  <h3 class="timeline-header"><span class="font-weigth-bold"><a class="text-white" href="#">{{ sede.nombre }} de {{ sede.lugar }}</a></h3>
                  <div class="timeline-body">
                    <p><b><i class="fas fa-envelope text-success"></i> Total Entregados:</b> {{ sede.total_entregadas }}</p>
                    <p><b><i class="fas fa-camera text-danger"></i> Total enrolados:</b> {{ sede.total_enrolados }}</p>
                    <p><b><i class="fas fa-home text-warning"></i> Total actualizados:</b> {{ sede.total_actualizados}}</p>
                  </div>
                  <div class="timeline-footer text-center justify-content-center">
                      <a class="btn btn-text btn-sm btn-primary" href="{% url 'Equipo:VerSede' sede.pk %}"><i class="fas fa-eye"></i>
                        <span class="d-none d-lg-inline">Visualizar</span>
                      </a>
                      {% if user.integrante.es_supervisor or user.is_staff %}
                      <a class="btn btn-text btn-sm btn-secondary" href="{% if sede.es_domiciliaria %}{% url 'Equipo:EditarDomiciliaria' sede.pk %}{% else %}{% url 'Equipo:EditarSede' sede.pk %}{% endif %}"><i class="fas fa-edit"></i>
                        <span class="d-none d-lg-inline">Editar</span>
                      </a>
                      <a class="btn btn-text btn-sm btn-danger" href="{% url 'Equipo:EliminarSede' sede.pk %}"><i class="fas fa-trash"></i>
                        <span class="d-none d-lg-inline">Eliminar</span>
                      </a>
                      {% endif %}
                  </div>
              </div>
           </div>
          {% endfor %}
	  {% empty %}
          {% endfor %}
          <div><i class="fas fa-calendar"></i></div>
      </div>
    </div>
    <div class="card-footer">
      {% include 'paginacion.html' %}
    </div>
  {% else %}
    <div class="card-body">
    <div class="alert alert-info">
      <h3><i class="fas fa-exclamation-triangle"></i> No hay sedes registradas</h3>
      <p>Al parecer no hay ninguna sede registrada o el término de búsqueda no encontró nada.</p>
    </div></div>
  </div>
  {% endif %}
</div>
{% endblock %}

app/Equipo/templates/ver-sede.html
{% extends 'base.html' %}

{% comment %}
PLANTILLA DE DETALLE DE SEDE

Visualiza una página detallando todas las actividades en la sede.

Autor: Carlos E. Rivera
Licencia: GPLv3
{% endcomment %}

{% block 'Titulo' %}Sede{% endblock %}
{% block 'TituloContenido' %}{{ object.nombre }} <small>de {{ object.lugar }}</small>{% endblock %}

{% block 'Contenido' %}
<div class="row justify-content-center mb-3">
	<div class="info-box col-md-3 mr-5">
		<span class="info-box-icon  bg-success elevation-1"><i class="fas fa-envelope"></i></span>
		<div class="info-box-content">
            <span class="info-box-text">Entregas DNI</span>
            <span class="info-box-number">{{ object.total_entregadas }}</span>
            <span class="info-box-number">Gran total: {{ gran_total_entrega}}</span>
		</div>
	</div>
	{% if object.total_enrolados != 0 %}
	<div class="info-box col-md-3 mr-5">
		<span class="info-box-icon  bg-danger elevation-1"><i class="fas fa-camera"></i></span>
		<div class="info-box-content">
            <span class="info-box-text">Enrolamientos</span>
            <span class="info-box-number">{{ object.total_enrolados }}</span>
            <span class="info-box-number">Gran total: {{ gran_total_enrol }}</span>
		</div>
	</div>
	{% endif %}
	{% if object.total_actualizados != 0 %}
	<div class="info-box col-md-3 mr-5">
		<span class="info-box-icon  bg-warning elevation-1"><i class="fas fa-home"></i></span>
		<div class="info-box-content">
            <span class="info-box-text">Actualizaciones</span>
            <span class="info-box-number">{{ object.total_actualizados}}</span>
            <span class="info-box-number">Gran total: {{ gran_total_actua }}</span>
		</div>
	</div>
	{% endif %}
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="card card-outline card-orange">
			<div class="card-header">
                <h3 class="card-title">Entregas por enrolador</h3>
			</div>
			<div class="card-body table-responsive">
                <table class="table table-hover">
                    <thead>
                        <th>Nombre</th>
                        <th>Entregados</th>
                        <th>Escaneados</th>
                    </thead>
                    <tbody>
                        {% for enrolador in enroladores|dictsortreversed:'entregados' %}
                        <tr>
                            <td>{{ enrolador.nombre }} {{ enrolador.apellido }}</td>
                            <td>{{ enrolador.entregados}}</td>
                            <td>{{ enrolador.escaneados}}</td>
                            {% empty %}
                            <div class="alert alert-info">
                                <h5><i class="fas fa-exclamation-triangle"></i> Sin registros</h5>
                                <p class="text-sm">No hay sobres entregados en esta sede</p>
                            </div>
                    	</tr>
                    	{% endfor %}
                    </tbody>
                </table>
            </div>
		</div>
	</div>
</div>
{% endblock %}